import { Course, Idea, Post, UserStats, User } from './types';

export const TRANSLATIONS = {
  zh: {
    dashboard: '仪表盘',
    marketplace: '资源广场',
    ideas: '搞钱思路',
    community: '创业社区',
    aiCoach: 'AI 商业教练',
    profile: '个人主页',
    welcome: '欢迎回来,',
    earnings: '总收入',
    sold: '分销/销量',
    rank: '社区等级',
    quickPost: '发布动态',
    trending: '热门风向',
    search: '搜索资源...',
    price: '价格',
    commission: '分销佣金',
    earn: '预估收益',
    getLink: '获取分销链接',
    publish: '发布专栏',
    createResource: '创建付费专栏',
    resourceTitle: '专栏/课程名称',
    resourceDesc: '简介 (支持 Markdown)',
    category: '分类',
    cancel: '取消',
    submit: '确认发布',
    genIdea: 'AI 挖掘思路',
    analyzing: '分析中...',
    difficulty: '难度',
    investment: '投入',
    firstStep: '第一步',
    askCoach: '向 AI 教练提问...',
    coachIntro: '我是您的 24/7 商业教练 WealthBot。我可以帮您分析商业模式、优化文案或解决流量问题。',
    saveProfile: '保存资料',
    uploadAvatar: '上传头像',
    bio: '个人简介',
    darkMode: '深色模式',
    lightMode: '浅色模式',
    whatsNew: '有什么新鲜事分享？',
    postPlaceholder: '分享你的创业心得、里程碑或求助...',
    publishPost: '发布动态',
    savedSuccess: '保存成功！',
    share: '分享',
    like: '点赞',
    comment: '评论',
    back: '返回',
    courseDetails: '课程详情',
    features: '课程亮点',
    targetAudience: '适合人群',
    copySuccess: '链接已复制到剪贴板！',
    sopTitle: '从 0 到 1 实操 SOP',
    toolsUsed: '使用工具',
    revenue: '月收入参考',
    timeToValidate: '验证周期',
    readMore: '阅读详情'
  },
  en: {
    dashboard: 'Dashboard',
    marketplace: 'Marketplace',
    ideas: 'Wealth Tactics',
    community: 'Community',
    aiCoach: 'AI Coach',
    profile: 'Profile',
    welcome: 'Welcome back,',
    earnings: 'Total Earnings',
    sold: 'Sales/Dist',
    rank: 'Rank',
    quickPost: 'Quick Post',
    trending: 'Trending',
    search: 'Search courses...',
    price: 'Price',
    commission: 'Commission',
    earn: 'You Earn',
    getLink: 'Get Affiliate Link',
    publish: 'Publish Resource',
    createResource: 'Create Paid Column',
    resourceTitle: 'Title',
    resourceDesc: 'Description',
    category: 'Category',
    cancel: 'Cancel',
    submit: 'Publish',
    genIdea: 'Generate Idea',
    analyzing: 'Analyzing...',
    difficulty: 'Difficulty',
    investment: 'Investment',
    firstStep: 'First Step',
    askCoach: 'Ask the coach...',
    coachIntro: 'I am WealthBot, your 24/7 business coach. I can help you analyze ideas, write copy, or solve traffic issues.',
    saveProfile: 'Save Profile',
    uploadAvatar: 'Upload Avatar',
    bio: 'Bio',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    whatsNew: "What's new?",
    postPlaceholder: 'Share your journey, milestones or ask for help...',
    publishPost: 'Post',
    savedSuccess: 'Saved Successfully!',
    share: 'Share',
    like: 'Like',
    comment: 'Comment',
    back: 'Back',
    courseDetails: 'Course Details',
    features: 'Features',
    targetAudience: 'Target Audience',
    copySuccess: 'Link copied to clipboard!',
    sopTitle: '0 to 1 SOP',
    toolsUsed: 'Tools Used',
    revenue: 'Revenue Reference',
    timeToValidate: 'Validation Time',
    readMore: 'Read More'
  }
};

export const MOCK_USER: User = {
  name: "独立开发者",
  role: "Indie Hacker",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Felix",
  bio: "专注小而美的产品开发，正在探索知识付费。",
  stats: {
    totalEarnings: 12450.00,
    coursesSold: 342,
    communityRank: "钻石合伙人"
  }
};

export const COURSES: Course[] = [
  {
    id: 'c1',
    title: '独立开发者全栈 SaaS 实战 2024',
    author: 'TechPreneur Academy',
    price: 199,
    commissionRate: 40,
    sales: 1205,
    category: 'Development',
    rating: 4.8,
    imageUrl: 'https://picsum.photos/400/250?random=1',
    description: '从零开始构建并扩展你的 SaaS 产品，使用 Next.js 和 AI 技术栈。',
    fullDescription: '本课程不仅仅是代码教程，更是一套完整的商业闭环指南。我们将带你从验证想法开始，通过 Landing Page 测试市场需求，使用 Next.js + Supabase + Stripe 快速搭建 MVP，最后通过 Product Hunt 发布并获取首批付费用户。包含大量实战源码和营销模板。',
    features: ['Next.js 14 App Router 实战', 'Stripe 支付集成', 'Product Hunt 发布清单', '冷启动邮件营销模板'],
    targetAudience: ['想做副业的前端工程师', '寻找技术合伙人的产品经理', '计算机专业学生']
  },
  {
    id: 'c2',
    title: 'TikTok 短视频爆款变现指南',
    author: 'Sarah Jenkins',
    price: 49,
    commissionRate: 50,
    sales: 8500,
    category: 'Marketing',
    rating: 4.5,
    imageUrl: 'https://picsum.photos/400/250?random=2',
    description: '30天内获得百万播放量的实战策略，适合零基础小白。',
    fullDescription: 'TikTok 是目前流量最大的红利平台。本专栏深入拆解 100 个爆款视频脚本，教你如何利用手机剪辑出高完播率的内容。特别包含"无人直播"带货和"创作者基金"变现的独家玩法。',
    features: ['0基础手机剪辑教程', '爆款脚本公式', '千粉账号起号流程', '带货选品逻辑'],
    targetAudience: ['内容创作者', '跨境电商卖家', '想通过短视频副业变现的人']
  },
  {
    id: 'c3',
    title: '自由职业文案写作致富课',
    author: 'WordSmith Pro',
    price: 129,
    commissionRate: 30,
    sales: 430,
    category: 'Writing',
    rating: 4.9,
    imageUrl: 'https://picsum.photos/400/250?random=3',
    description: '掌握高客单价文案技能，逃离朝九晚五，实现地理套利。',
    fullDescription: '好的文案值千金。在这个 AI 时代，具有人类情感和转化逻辑的文案更加稀缺。本课程教授直复营销（Direct Response）文案的核心秘籍，教你如何写出让客户无法拒绝的销售信和着陆页文案。',
    features: ['高转化着陆页拆解', '邮件营销序列编写', '如何在这个 AI 时代保持竞争力', '自由职业接单渠道大公开'],
    targetAudience: ['自由职业者', '市场营销人员', '数字游民']
  },
  {
    id: 'c4',
    title: 'AI 自动化代理商 (AAA) 创业落地',
    author: 'Future Works',
    price: 299,
    commissionRate: 25,
    sales: 210,
    category: 'AI Business',
    rating: 4.7,
    imageUrl: 'https://picsum.photos/400/250?random=4',
    description: '为本地企业提供 AI 自动化服务，建立高利润的 B2B 代理商业务。',
    fullDescription: 'AI Automation Agency (AAA) 是 2024 年最大的 B2B 机会。无需编程基础，利用 Make.com (Integromat) 和 Zapier，帮企业搭建 AI 客服、自动线索抓取系统。我们将提供完整的销售话术和合同模板。',
    features: ['No-Code 自动化工作流搭建', '企业级 AI 客服机器人开发', 'B2B 销售话术与合同', '月入 $10k 的定价策略'],
    targetAudience: ['寻找高客单价业务的创业者', 'B2B 销售', '无代码开发者']
  }
];

export const IDEAS: Idea[] = [
  {
    id: 'i1',
    title: '利基市场付费通讯录 (Newsletter)',
    author: 'GrowthHacker_99',
    tags: ['Newsletter', 'Marketing', 'Passive'],
    difficulty: 'Medium',
    investment: 'Low',
    likes: 342,
    content: '针对特定微小众领域（如：垂直园艺设备、复古键盘）制作精选周刊，通过分销链接和赞助变现。参考"小报童"模式。',
    timestamp: '2 小时前',
    monthlyRevenue: '$2,000 - $5,000',
    validationTime: '2-4 周',
    tools: ['Substack / Beehiiv', 'Twitter/X', 'Gumroad'],
    sop: [
      { title: '发现利基', description: '寻找 Reddit 或 Twitter 上讨论热度高但缺乏高质量整合信息的领域。例如"Notion 模板创作者"或"复古相机玩家"。' },
      { title: '构建着陆页', description: '使用 Carrd 制作一个单页，简单介绍 Newsletter 的价值（例如：每周为你节省 10 小时筛选时间），并提供"订阅等待名单"。' },
      { title: '冷启动流量', description: '在相关的 Reddit 社区发帖分享干货，文末附上订阅链接。私信该领域的 50 个微型 KOL 寻求互推。' },
      { title: '内容生产 SOP', description: '周一到周四：使用 RSS 阅读器聚合行业新闻；周五：花 2 小时筛选 5 条最有价值的信息并撰写简评；周六：排版发送。' },
      { title: '变现闭环', description: '当订阅达到 500 人时，开启付费版（提供深度报告）或接相关的赞助广告。' }
    ]
  },
  {
    id: 'i2',
    title: '牙科诊所本地 SEO 服务',
    author: 'AgencyBuilder',
    tags: ['Service', 'B2B', 'High Ticket'],
    difficulty: 'Hard',
    investment: 'Low',
    likes: 128,
    content: '牙医客户终身价值高。提供专门针对牙科诊所的"Google Maps 排名优化"套餐，容易切入。',
    timestamp: '5 小时前',
    monthlyRevenue: '$5,000+',
    validationTime: '1 个月',
    tools: ['Google Business Profile', 'BrightLocal', 'Cold Email'],
    sop: [
      { title: '选定区域', description: '选择人口密集但竞争尚未白热化的二线城市区域。' },
      { title: '客户清单', description: '在 Google Maps 上搜索 Dentist，找出那些评分在 4.5 以下或者没有认领商家信息的诊所。' },
      { title: '价值前置', description: '录制一个 3 分钟的 Loom 视频，直接指出他们目前排名低的原因（如照片缺失、回复不及时），并发给诊所老板。' },
      { title: '服务交付', description: '优化 GMB 资料，上传高质量诊所照片，建立本地引用（Citations），设置自动回复评论系统。' }
    ]
  },
  {
    id: 'i3',
    title: 'AI 生成特定文化素材库',
    author: 'CreativeAI',
    tags: ['AI', 'Digital Assets'],
    difficulty: 'Easy',
    investment: 'Medium',
    likes: 890,
    content: '使用 Midjourney v6 生成目前主流图库中缺失的特定亚洲文化场景素材，上传到 Adobe Stock 销售。',
    timestamp: '1 天前',
    monthlyRevenue: '$300 - $1,500',
    validationTime: '1 周',
    tools: ['Midjourney', 'Adobe Stock', 'Upscale 工具'],
    sop: [
      { title: '图库调研', description: '浏览 Shutterstock 或 Adobe Stock，搜索"Traditional Chinese Festival"等关键词，寻找那些看起来很假、由西方人拍摄的素材。' },
      { title: 'Prompt 调试', description: '使用 MJ v6 调试出一套写实风格的 Prompt，重点在于光影控制和细节纹理。' },
      { title: '批量生成与筛选', description: '每晚挂机生成 200 张图，第二天人工筛选出 20 张无瑕疵（如手指正常）的图片。' },
      { title: '放大与上传', description: '使用 Topaz Gigapixel 放大图片至 4K，编写详细的英文 Tag，上传至多个图库平台。' }
    ]
  }
];

export const POSTS: Post[] = [
  {
    id: 'p1',
    author: 'David Chen',
    authorRole: 'SaaS Founder',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    content: '我的微型 SaaS 刚刚突破 $5k MRR！关键在于先把分销渠道铺好，而不是死磕代码。还有谁在 Build in Public？',
    likes: 45,
    isLiked: true,
    comments: 12,
    timestamp: '10 分钟前',
    tags: ['#buildinpublic', '#saas']
  },
  {
    id: 'p2',
    author: 'Elena Rossi',
    authorRole: 'Freelancer',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena',
    content: '正在寻找一个 FinTech 想法的技术合伙人。我有领域专长和销售渠道，需要人搞定 MVP。',
    likes: 23,
    isLiked: false,
    comments: 8,
    timestamp: '1 小时前',
    tags: ['#合伙人', '#networking']
  },
  {
    id: 'p3',
    author: 'Mike Ross',
    authorRole: 'Affiliate Marketer',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    content: '有人试过那个"TikTok 爆款"课程吗？想投点流试试。50% 的佣金看起来很香。',
    likes: 15,
    isLiked: false,
    comments: 24,
    timestamp: '3 小时前',
    tags: ['#分销', '#测评']
  }
];